version: '3'
services:
    mongo:
      image: 'mongo:3.4.1'
      ports:
        - '27017:27017'
      volumes:
        - 'mongo:/data/db'

    # Django
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile
        hostname: scrapy_news
        command: ./docker/run_scrapy_news.sh
        volumes:
            - .:/code:Z
        ports:
            - "6800:6800"
        links:
            - mongo
        depends_on:
            - mongo
volumes:
    mongo: